---
- name: restart act_runner
  become: true
  ansible.builtin.systemd:
    name: act_runner
    state: restarted
    daemon_reload: true

- name: restart podman socket
  become: true
  ansible.builtin.systemd:
    name: podman.socket
    state: restarted
    daemon_reload: true
